config/routes.rb
Rails.application.routes.draw do
  resources :receipts

  get '/receipt/:id/copy' ,to:'receipts#copy'
  root 'receipts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :receipt
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :receipt

  def total_price
    qty.to_i * cost.to_f
  end
end

app/models/receipt.rb
class Receipt < ApplicationRecord
    has_many :items, inverse_of: :receipt, :dependent => :destroy
    has_one :customer , :dependent => :destroy
    has_one :seller, :dependent => :destroy
    accepts_nested_attributes_for :items,allow_destroy: true,reject_if: :all_blank
    attr_accessor :cus_name,:cus_address,:cus_order_id,:cus_payment_method #customer
    attr_accessor :sel_name,:sel_address,:sel_vat_id,:sel_business_id #seller
    after_commit :save_details, on: [:create, :update]
    amoeba do
        enable
      end

      #save customer and seller after create receipt
      def save_details
        Customer.create name: cus_name,address: cus_address , payment_method: cus_payment_method,order_id: cus_order_id,receipt: self
        Seller.create name: cus_name,address: cus_address , vat_id: sel_vat_id,business_id: sel_business_id,receipt: self
      end
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :receipt
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: %i[ show edit update destroy copy]

  # GET /receipts or /receipts.json
  def index
    @receipts = Receipt.all
  end

  # GET /receipts/1 or /receipts/1.json
  def show
  end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
    # @receipt.customer.build
  end

  # GET /receipts/1/edit
  def edit
  end

  # Create New Receipt
  def create
    @receipt = Receipt.new(receipt_params)
    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: "Receipt was successfully created." }
        format.json { render :show, status: :created, location: @receipt }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts/1 or /receipts/1.json
  def update
    respond_to do |format|
      if @receipt.update(receipt_params)
        format.html { redirect_to @receipt, notice: "Receipt was successfully updated." }
        format.json { render :show, status: :ok, location: @receipt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1 or /receipts/1.json
  def destroy
    @receipt.destroy
    respond_to do |format|
      format.html { redirect_to receipts_url, notice: "Receipt was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #Copy Receipt with all item.
  def copy
    receipt_copy = @receipt.amoeba_dup
    receipt_copy.save
    @receipt.items.destroy_all
    respond_to do |format|
      format.html { redirect_to receipts_url, notice: "Receipt was successfully copyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def receipt_params
      params.require(:receipt).permit(:name,:cus_name,:cus_address,:cus_payment_method,:cus_order_id,:sel_name,:sel_address,:sel_vat_id,:sel_business_id,items_attributes: [:id, :name, :qty, :cost,:_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def link_to_add_fields(name, form, association)
        new_object = form.object.send(association).klass.new
        id = new_object.object_id
        fields = form.fields_for(association, new_object, child_index: id) do |builder|
            render(association.to_s.singularize + "_fields", form: builder)
        end
        link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
    end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReceptBuilding</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>

  </head>

  <body>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/receipts/_customer_fields.html.erb
<div class="nested-fields">
<%- if @receipt.customer %>

<div class="field">
<%= form.label :cus_name %>
<%= form.text_field :cus_name,:value => @receipt.customer.name %>
</div>
<div class="field">
<%= form.label :cus_address %>
<%= form.text_field :cus_address,:value => @receipt.customer.address %>
</div>
<div class="field">
<%= form.label :cus_order_id %>
<%= form.text_field :cus_order_id,:value => @receipt.customer.order_id %>
</div>
<div class="field">
<%= form.label :cus_payment_method %>
<%= form.text_field :cus_payment_method ,:value => @receipt.customer.payment_method %>
</div>
<%- else %>

<div class="field">
<%= form.label :cus_name %>
<%= form.text_field :cus_name%>
</div>
<div class="field">
<%= form.label :cus_address %>
<%= form.text_field :cus_address %>
</div>
<div class="field">
<%= form.label :cus_order_id %>
<%= form.text_field :cus_order_id %>
</div>
<div class="field">
<%= form.label :cus_payment_method %>
<%= form.text_field :cus_payment_method%>
</div>

<% end %>

</div>

app/views/receipts/_form.html.erb
<%= form_with(model: receipt,html: {id: 'myForm' }) do |form| %>
  <% if receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
        <% receipt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <fieldset>
  <legend>List items:</legend>
  <%= form.fields_for :items do |item_form| %>
      <%= render "item_fields", form: item_form %>
  <% end %>
  <%= link_to_add_fields "Add list", form, :items %>
</fieldset>

<br />

<h2>Customer Details</h2>
    <%= render "customer_fields", form: form %>

<br />
<h2>Seller Details</h2>
    <%= render "seller_fields", form: form %>



  <div class="actions">
    <%= form.submit  %>
  </div>
<% end %>

<script>
$(document).ready(function(){
 console.log('here')
$("#myForm").validate({
rules: {
"receipt[cus_name]": {
required: true
},
"receipt[cus_address]": {
required: true
},
"receipt[cus_order_id]": {
required: true
},
"receipt[cus_payment_method]": {
required: true
},
"receipt[sel_name]": {
required: true
},
"receipt[sel_address]": {
required: true,
        },
"receipt[sel_vat_id]": {
required: true
},
"receipt[business_id]": {
required: true
},
"receipt[name]": {
required: true
},


},

submitHandler: function (form) {
return true;
}
});
});
</script>


<style>
.create_recept_sec {
    width: 60%;
    margin: auto;
}
.create_recept_sec h1 {
    text-align: center;
}
form#myForm .field {
    width: 48%;
}
 form#myForm .field label {
    font-size: 18px;
    margin-bottom: 10px;
}
form#myForm .field input {
    width: 100%;
    height: 28px;
    border: 1px solid #ddd;
}
.nested-fields .field {
    padding: 0 10px;
}
form#myForm fieldset {
    border: 1px solid #ddd;
}
form#myForm fieldset legend {
    font-size: 18px;
}
form#myForm fieldset  .nested-fields {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}
form#myForm fieldset .nested-fields div {
    flex: 0 0 48%;
    padding: 0 10px;
    max-width: 48%;
}
form#myForm fieldset .nested-fields div label {
    font-size: 18px;
    margin-bottom: 10px;
    margin-top: 10px;
}
form#myForm fieldset .nested-fields div input {
    width: 100%;
    height: 28px;
    border: 1px solid #ddd;
}
.nested-fields {
    display: flex;
    flex-wrap: wrap;
}
h2{
    margin-top:0px;
}
form#myForm fieldset a.add_fields , form#myForm fieldset  a.remove_fields{ 
    font-size: 18px;
    text-decoration: none;
}
.actions input[type="submit"] {
    background-color: #000;
    display: flex;
    justify-content: center;
    margin: auto;
    color: #fff;
    font-size: 18px;
    padding: 10px 15px;
    border: none;
    margin-top: 15px;
}
label#receipt_name-error {
    margin-top: 10px;
    color: red;
}
a.remove_fields {
    margin-top: 10px;
    display: inline-block;
    margin-bottom: 10px;
}
a.remove_fields {
    margin-top: 10px;
    display: inline-block;
    margin-bottom: 10px;
}
form#myForm fieldset .nested-fields div:last-child {
    flex: 0 0 100%;
    max-width: 100%;
}
form#myForm fieldset a.add_fields {
    padding: 0 10px;
}
.create_recept_sec a:last-child {
    text-align: center;
    display: flex;
    justify-content: center;
    font-size: 19px;
    color: #000;
}
a:hover{
    background-color:transparent;
}
</style>

app/views/receipts/_item_fields.html.erb
<div class="nested-fields">
<%= form.hidden_field :_destroy %>

    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>
    <div>
        <%= form.label :qty %>
        <%= form.text_field :qty %>
    </div>
    <div>
        <%= form.label :cost %>
        <%= form.text_field :cost %>
    </div>
    <div>
        <%= link_to "Remove", '#', class: "remove_fields" %>
    </div>
</div>

app/views/receipts/_seller_fields.html.erb
<div class="nested-fields">
<%- if @receipt.seller %>
<div class="field">
<%= form.label :sel_name %>
<%= form.text_field :sel_name,:value => @receipt.seller.name %>
</div>
<div class="field">
<%= form.label :sel_address %>
<%= form.text_field :sel_address ,:value => @receipt.seller.address %>
</div>
<div class="field">
<%= form.label :sel_vat_id %>
<%= form.text_field :sel_vat_id ,:value => @receipt.seller.vat_id %>
</div>
<div class="field">
<%= form.label :business_id %>
<%= form.text_field :sel_business_id,:value => @receipt.seller.business_id %>
</div>

<%- else %>

<div class="field">
<%= form.label :sel_name %>
<%= form.text_field :sel_name %>
</div>

<div class="field">
<%= form.label :sel_address %>
<%= form.text_field :sel_address %>
</div>

<div class="field">
<%= form.label :sel_vat_id %>
<%= form.text_field :sel_vat_id %>
</div>

<div class="field">
<%= form.label :business_id %>
<%= form.text_field :sel_business_id %>
</div>

<% end %>

</div>

app/views/receipts/edit.html.erb
<h1>Editing Receipt</h1>

<%= render 'form', receipt: @receipt %>
<div class="recipt_btn">
<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>
</div>

<style>

.recipt_btn {
    text-align: center;
    width: 50%;
    margin: auto;
    margin-top: 30px;
}
.recipt_btn a {
    padding: 10px 20px;
    background-color: #000;
    color: #fff;
    text-decoration: none;
    font-size: 16px;
    display: inline-block;
}
.recipt_btn a:last-child {
background-color:#898989;
}
.seller_details_sec bt:nth-child(3) {
    margin: 20px 0;
    display: block;
}
</style>

app/views/receipts/index.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<div class="recipt_sec">
<div class="recipt_iiner_sec">

<p id="notice"><%= notice %></p>

<h2>Receipts</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col" >Name</th>
      <th  scope="col"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.name %></td>
        <td><%= link_to 'Show', receipt %></td>
        <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
        <td><%= link_to 'Destroy', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Copy', "/receipt/#{receipt.id}/copy" %></td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>


<div class="recipt_btn">

<%= link_to 'New Receipt', new_receipt_path %>
</div>
</div>
<style>

.recipt_btn a {
    padding: 10px 20px;
    background-color: #000;
    color: #fff;
    text-decoration: none;
    font-size: 16px;
    display: inline-block;
}

.seller_details_sec bt:nth-child(3) {
    margin: 20px 0;
    display: block;
}


.recipt_btn {
    text-align: center;
    width: 50%;
    margin: auto;
    margin-top: 30px;
}
.recipt_btn a {
    padding: 10px 20px;
    background-color: #000;
    color: #fff;
    text-decoration: none;
    font-size: 16px;
    display: inline-block;
}
.recipt_btn a:last-child {
background-color:#898989;
}
.seller_details_sec bt:nth-child(3) {
    margin: 20px 0;
    display: block;
}
</style>

app/views/receipts/new.html.erb
<div class="create_recept_sec">
<h1>New Receipt</h1>

<div class="recipt_btn">

<%= render 'form', receipt: @receipt %>

<%= link_to 'Back', receipts_path %>
</div>
</div>

app/views/receipts/show.html.erb
<div class="recipt_sec">
<div class="recipt_iiner_sec">
<p id="notice"><%= notice %></p>
<h3>Wolt Delivery Receipt</h3>
<p><%= @receipt.seller.created_at.strftime("%d.%m.%Y") %></p>
</div>

<div class="receipt_table_sec">
<table border-collapse: "collapse" cellpadding="0"  cellspacing="0"
    <tr>
      <th>ITEM</th>
      <th>Total</th>
    </tr>
  </thead>

  <tbody>
    <% @receipt.items.each do |item| %>
      <tr>
        <td><%= item.name %> (<%= item.qty %>)</td>
        <td><%= (item.qty.to_i)*(item.cost.to_i) %></td>

        
      </tr>
    <% end %>
    <tr>
      <td >Subtotal excl. VAT</td>
      <td>0.08</td>
    </tr>
    <tr>
      <td >VAT 20% </td>
      <td>0.08</td>
    </tr>
    <tr class="total_Sesc">
      <td>Total </td>

      <td><%= @receipt.items.map(&:total_price).reduce(0, :+) %></td>
    </tr>
  </tbody>
</table>
</div>
<br />
<div class="seller_details_sec">
<h4>Seller Details</h4>
<p>date and time : <span> <%= @receipt.seller.created_at.strftime("%A %d %^b %T %Y") %> </span> </p><bt />

<p><strong>Seller : </strong> <span> <%= @receipt.seller.name %> </span> </p><bt />
<p><strong>VAT ID : </strong> <span> <%= @receipt.seller.vat_id %> </span> </p><bt />
<p><strong>Business ID : </strong> <span> <%= @receipt.seller.business_id %> </span> </p><bt />
<p><strong>Address : </strong> <span> <%= @receipt.seller.address %> </span> </p><bt />

<br />
<h4>Customer details</h4>

<p><strong>Customer : </strong> <span> <%= @receipt.customer.name %> </span> </p><bt />
<p><strong>Payment method : </strong> <span> <%= @receipt.customer.payment_method %> </span> </p><bt />
<p><strong>Order ID : </strong> <span> <%= @receipt.customer.order_id %> </span> </p><bt />
<p><strong>Delivery Address : </strong> <span> <%= @receipt.customer.address %> </span> </p><bt />
</div>
<div class="recipt_btn">
<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back', receipts_path %>
</div>
</div>

<style>
.recipt_sec .recipt_iiner_sec {
    text-align: center;
}
.recipt_sec .recipt_iiner_sec h3 {
    font-size: 25px;
    font-weight: 900;
}
.recipt_sec .recipt_iiner_sec p {
    font-size: 20px;
}
.receipt_table_sec table tr  th {
    font-size: 22px;
    border-bottom: 2px solid #b8b8b8;
    text-align: left;
    padding-bottom: 10px;
}
.receipt_table_sec table tr th:last-child {
    text-align: right;
}
.receipt_table_sec table {
    width: 50%;
    margin: auto;
}
.receipt_table_sec table tbody tr td:last-child {
    text-align: right;
}
.receipt_table_sec table tbody tr td {
    font-size: 20px;
    padding-left: 0;
    padding-right: 0;
    padding-top: 10px;
    border-bottom: 2px solid #f5f5f5;
    padding-bottom: 10px;
}
.receipt_table_sec table tr:nth-child(2) td {
    border-bottom: 2px solid #b8b8b8;
}
.receipt_table_sec table tr.total_Sesc td {
    font-weight: bold;
}
.seller_details_sec {
    width: 50%;
    margin: auto;
    margin-top: 30px;
}
tr.total_Sesc td {
    border-bottom: none! important;
    border-top: 2px solid #b8b8b8;
}
.seller_details_sec h4 {
    margin: 0;
    color: #898989;
    font-size: 22px;
    font-weight: 900;
    text-transform: uppercase;
}
.seller_details_sec p {
    color: #898989;
    font-size: 22px;
    text-transform: capitalize;
    margin-top: 8px;
    margin-bottom: 8px;
}
.recipt_btn {
    text-align: center;
    width: 50%;
    margin: auto;
    margin-top: 30px;
}
.recipt_btn a {
    padding: 10px 20px;
    background-color: #000;
    color: #fff;
    text-decoration: none;
    font-size: 16px;
    display: inline-block;
}
.recipt_btn a:last-child {
background-color:#898989;
}
.seller_details_sec bt:nth-child(3) {
    margin: 20px 0;
    display: block;
}
</style>